// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/li1553770945/sheepim-push-proxy-service/biz/infra/config"
	"github.com/li1553770945/sheepim-push-proxy-service/biz/infra/kafka"
	"github.com/li1553770945/sheepim-push-proxy-service/biz/infra/log"
	"github.com/li1553770945/sheepim-push-proxy-service/biz/infra/trace"
	"github.com/li1553770945/sheepim-push-proxy-service/biz/internal/repo"
	"github.com/li1553770945/sheepim-push-proxy-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(env string) *Container {
	configConfig := config.GetConfig(env)
	traceLogger := log.InitLog()
	traceStruct := trace.InitTrace(configConfig)
	kafkaClient := kafka.NewKafkaClient(configConfig)
	iRepository := repo.NewRepository(kafkaClient)
	iPushProxyService := service.NewPushProxyService(iRepository)
	container := NewContainer(configConfig, traceLogger, traceStruct, kafkaClient, iPushProxyService)
	return container
}
