// Code generated by Kitex v0.7.2. DO NOT EDIT.

package pushproxyservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	push_proxy "github.com/li1553770945/sheepim-push-proxy-service/kitex_gen/push_proxy"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushMessage(ctx context.Context, req *push_proxy.PushMessageReq, callOptions ...callopt.Option) (r *push_proxy.PushMessageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPushProxyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPushProxyServiceClient struct {
	*kClient
}

func (p *kPushProxyServiceClient) PushMessage(ctx context.Context, req *push_proxy.PushMessageReq, callOptions ...callopt.Option) (r *push_proxy.PushMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushMessage(ctx, req)
}
