// Code generated by Kitex v0.7.2. DO NOT EDIT.
package pushproxyservice

import (
	server "github.com/cloudwego/kitex/server"
	push_proxy "github.com/li1553770945/sheepim-push-proxy-service/kitex_gen/push_proxy"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler push_proxy.PushProxyService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
